version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: messaging_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_password
      MYSQL_DATABASE: messaging_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging_django
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py loaddata seed &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_password
      MYSQL_DB: messaging_db

volumes:
  mysql_data:
